// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/UI/BaseButton.vue')['default']
    BaseCard: typeof import('./components/UI/BaseCard.vue')['default']
    BaseFileProgress: typeof import('./components/UI/BaseFileProgress.vue')['default']
    BaseInput: typeof import('./components/UI/BaseInput.vue')['default']
    BaseModal: typeof import('./components/UI/BaseModal.vue')['default']
    BaseSelect: typeof import('./components/UI/BaseSelect.vue')['default']
    IconBack: typeof import('./components/Icons/IconBack.vue')['default']
    IconCheck: typeof import('./components/Icons/IconCheck.vue')['default']
    IconMoon: typeof import('./components/Icons/IconMoon.vue')['default']
    IconNext: typeof import('./components/Icons/IconNext.vue')['default']
    IconPlus: typeof import('./components/Icons/IconPlus.vue')['default']
    IconSun: typeof import('./components/Icons/IconSun.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/layouts/TheHeader.vue')['default']
  }
}

export {}
